config/routes.rb
Rails.application.routes.draw do
  resources :appointments
  resources :veterinarians
  resources :pets do 
    #nested routes
    resources :veterinarians, only: [:index]
    resources :appointments, only: [:index, :new]
  end
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'pets#index'
end

app/models/veterinarian.rb
class Veterinarian < ApplicationRecord
    #associations
    has_many :appointments
    has_many :pets, through: :appointments
    
    #validations
    validates :name, :phone_number, :specializations, presence: true
    
end

app/controllers/veterinarians_controller.rb
class VeterinariansController < ApplicationController
    before_action :authenticate_user!
    before_action :set_vet, only: [:show, :edit, :update, :destroy]

    def index
        @veterinarians = Veterinarian.all
    end

    def show
        # @ = .find()
    end

    def new
        @veterinarian = Veterinarian.new
    end

    def create
         @veterinarian = Veterinarian.new(vet_params)
            if @veterinarian.save 
                redirect_to veterinarian_path(@veterinarian)
            else
                render :new
            end
    end

    private

    def set_vet
        @veterinarian = Veterinarian.find(
        params[:id]
        )
    end

    def vet_params
        params.require(:veterinarian).permit(:name, :phone_number, :specializations)
    end

end

app/helpers/veterinarians_helper.rb
module VeterinariansHelper
end

app/views/veterinarians/index.html.erb
<h1> Veterinarians List </h1>

<button><%= link_to 'Add Veterinarian', new_veterinarian_path %></button>

<% @veterinarians.each do |veterinarian| %>
<p><%= link_to veterinarian.name, veterinarian_url(veterinarian) %></p>

<% end %>

app/views/veterinarians/new.html.erb
<h1> New Vet </h1>

<%= show_errors_for(@veterinarian) %>
<%= form_for @veterinarian do |f| %>

<p>
    <%= f.label :name %>
    <%= f.text_field :name %>
</p>

<p> 
    <%= f.label :phone_number %>
    <%= f.text_field :phone_number %>
</p>

<p> 
    <%= f.label :specializations %>
    <%= f.text_area :specializations %>
</p>

<%= f.submit %>
<% end %>

app/views/veterinarians/show.html.erb
<h1><%= @veterinarian.name %></h1>

<p> <%= link_to "Book with #{@veterinarian.name}", new_pet_appointment_path(@veterinarian) %></p>
<p> <%= link_to "#{@veterinarian.name}'s appointment", pet_appointments_path(@veterinarian) %></p>