config/routes.rb
Rails.application.routes.draw do
  resources :appointments
  resources :veterinarians
  resources :pets do 
    #nested routes
    resources :veterinarians, only: [:index]
    resources :appointments, only: [:index, :new]
  end
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'pets#index'
end

app/models/pet.rb
class Pet < ApplicationRecord
  belongs_to :user
  has_many :appointments
  has_many :doctors, through: :appointments

  validates :name, presence: true, uniqueness: {scope: :user_id}
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController

    #helper from devise
    before_action :authenticate_user!
    #Looking only at files the user created
    before_action :set_pet, only: [:show, :edit, :update, :destroy]

    def index
        #collection of all current_user pets
        @pets = current_user.pets
    end

    def show
        
    end

    def new
        @pet = Pet.new
    end

    def create
        #call build on current user to get ID
        #works because has_many
        @pet = current_user.pets.build(pet_params)
            if @pet.save 
                redirect_to pet_path(@pet)
            else
                render :new
            end
    end
    
    def edit
        #form_for works the same from update/edit
    end
    
    def update
        if @pet.update(pet_params)
            redirect_to pet_path(@pet)
        else
            render :edit
        end
    end
    
    def destroy
        @pet.destroy
        redirect_to pets_path
    end
    
end


private_methods
#So we don't have to use this over and over
def set_pet
    @pet = current_user.pets.find(params[:id])
end

#whitelist attributes
def pet_params
    params.require(:pet).permit(:name)
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/pets/_form.html.erb
<%= show_errors_for(pet) %>

<%= form_for pet do |f| %>

<p>
    <%= f.label :name,  "Pet Name" %><br/>
    <%= f.text_area :name %>
    <%= f.submit %>
</p>

<% end %>

app/views/pets/edit.html.erb
<h1>Edit Pet</h1>
<%= render partial: 'form', locals: {pet: @pet } %>

app/views/pets/index.html.erb
<h1>Pets List</h1>

<button><%= link_to 'Add Pet', new_pet_path %></button>

<% @pets.each do |pet| %>
<p><%= link_to pet.name, pet_url(pet) %></p>

<% end %>

app/views/pets/new.html.erb
<h1>New Pet</h1>

<%= render partial: 'form', locals: {pet: @pet } %>

app/views/pets/show.html.erb
<h1><%= @pet.name %></h1>

<p>
<%= link_to "Edit", edit_pet_path(@pet) %>

<%= form_tag(pet_path(@pet), method: :delete) do %>
<%= submit_tag "Delete Pet" %>

<%= link_to "#{@pet.name}'s appointments", pet_appointments_path(@pet) %>
<%= link_to "Book Appointment for #{@pet.name}", new_pet_appointment_path(@pet) %>
<% end %>

</p>