config/routes.rb
Rails.application.routes.draw do
  resources :appointments
  resources :veterinarians
  resources :pets do 
    #nested routes
    resources :veterinarians, only: [:index]
    resources :appointments, only: [:index, :new]
  end
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'pets#index'
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :veterinarian
  belongs_to :pet

  validates :start_time, :end_time, :location, presence: true
  validate :vet_overlap, :pet_overlap, if: :starts_before_it_ends?
  validate :ends_after_it_starts
  
#Don't forget about doublebooking the appointments
  def vet_overlap
    this_start = self.start_time
    this_end = self.end_time
    return if this_end < this_start
    overlap = veterinarian.appointments.any? do |appointment|
      other_start = appointment.start_time
      other_end = appointment.end_time
      other_start < this_end && this_end < other_end || other_start < this_start && this_start < other_end
    end
    if overlap
      errors.add(:veterinarian, 'has a conflicting appointment')
    end
  end
#What if the pet is doublebooked
  def pet_overlap
    this_start = self.start_time
    this_end = self.end_time
    overlap = veterinarian.appointments.any? do |appointment|
      other_start = appointment.start_time
      other_end = appointment.end_time
      other_start < this_end && this_end < other_end || other_start < this_start && this_start < other_end
    end
    if overlap
      errors.add(:pet, 'has a conflicting appointment')
    end
  end
#keeps appointments straight (ends after start, start after ends)
  def ends_after_it_starts
    if !starts_before_it_ends?
      errors.add(:start_time, 'must be before the end time')
    end
  end

  def starts_before_it_ends?
    start_time < end_time
  end

#define doctor to use on appointment index view
  def vet_name
    self.veterinarian.name
  end

  def pet_name
    self.pet.name
  end

#scope method returns all appointments for input vet
  def self.by_vet(veterinarian)
    where(veterinarian_id: veterinarian.id)
  end
#this is a scope
  def self.upcoming
    where("start_time > ?", Time.now)
  end
#this is a scope
  def self.past 
    where("start_time < ?", Time.now)
  end
#this is a scope
  def self.most_recent
    order(start_time: :desc)
  end
#this is a scope
  def self.longest_ago
    order(start_time: :asc)
  end

end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_appointment, only: [:show, :edit, :update, :destroy]

    def index
        @pet = current_user.pets.find_by_id(params[:pet_id])
        @veterinarian = Veterinarian.find_by_id(params[:pet_id])
        #conditional logic for nested route
        if @pet
            @appointments = @pet.appointments
        elsif @veterinarian 
            @appointments = current_user.appointments.by_vet(@veterinarian)
        else
            @appointments = current_user.appointments
        end
        filter_options
    end

    def show
    end

    def new
        @pet = current_user.pets.find_by_id(params[:pet_id])
        @veterinarian = Veterinarian.find_by_id(params[:veterinarian_id])
        
        if @pet
            @appointment = @pet.appointments.build
        elsif @veterinarian 
            @appointment = @veterinarian.appointments.build
        else
            @appointment = Appointment.new
        end
    end

    def create 
        #this one is tricky, can't use build, not direct relation
        @appointment = Appointment.new(appointment_params)
            if @appointment.save
                redirect_to appointment_path(@appointment)
            else
                render :new
            end
    end

    def edit
    end

    def update 
        if @appointment.update(appointment_params)
            redirect_to appointment_path(@appointment)
        else
            render :edit
        end
    end

    def destroy 
        @appointment.destroy
        redirect_to appointments_path
    end

    private

    def set_appointment
        @appointment = current_user.appointments.find(
        params[:id]
        )
    end

    def filter_options
        if params[:filter_by_time] == "upcoming"
            @appointments = @appointments.upcoming
        elsif params[:filter_by_time] == "past"
            @appointments = @appointments.past
        end
        if params[:sort] == "most recent"
            @appointments = @appointments.most_recent
        elsif params[:sort] == "longest ago"
            @appointments = @appointments.longest_ago
        end
    end

    def appointment_params
        params.require(:appointment).permit(:start_time, :end_time, :location, :veterinarian_id, :pet_id)
    end

end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/appointments/_form.html.erb
<%= show_errors_for(appointment) %>

<%= form_for appointment do |f| %>

<p>
    <% if appointment.pet_id %>
        <%= f.label :pet_id, "Pet" %>
        <%= f.hidden_field :pet_id %>
        <%= appointment.pet.name %>
    <% else %>
        <%= f.label :pet_id, "Pet" %>
        <%= f.collection_select :pet_id, current_user.pets, :id, :name %>
    <% end %>
</p>

<p>
    <% if appointment.veterinarian_id %>
        <%= f.label :veterinarian_id, "Veterinarian" %>
        <%= f.hidden_field :veterinarian_id %>
        <%= appointment.veterinarian.name %>
    <% else %>
        <%= f.label :veterinarian_id, "Veterinarian" %>
        <%= f.collection_select :veterinarian_id, Veterinarian.all, :id, :name %>
    <% end %>
</p>

<p>
    <%= f.label :location %>
    <%= f.text_field :location %>
</p>

<p>
    <%= f.label :start_time %>
    <%= f.datetime_field :start_time %>
</p>

<p>
    <%= f.label :end_time %>
    <%= f.datetime_field :end_time %>
</p>

<%= f.submit %>
<% end %>

app/views/appointments/edit.html.erb
<h1>Edit Appointment</h1>
<%# render parial %>
<%= render partial: 'form', locals: { appointment: @appointment } %>

app/views/appointments/index.html.erb
<h1>Appointments</h1>

<button><%= link_to "Add Appointment", new_appointment_path %></button>

<%= form_tag(appointments_path, method: 'get') do %>

<label for="filter_by_time">Filter By Time</label>
<select name="filter_by_time">
    <option <%= 'selected' if params[:filter_by_time] == '' %> value="">All</option>
    <option <%= 'selected' if params[:filter_by_time] == 'past' %> value="past">Past</option>
    <option <%= 'selected' if params[:filter_by_time] == 'upcoming' %> value="upcoming">Upcoming</option>
</select>
<label for="sort">Sort</label>
<select name="sort">
    <option <%= 'selected' if params[:sort] == '' %> value="">None</option>
    <option <%= 'selected' if params[:sort] == 'most_recent' %> value="most_recent">Most Recent</option>
    <option <%= 'selected' if params[:sort] == 'longest_ago' %> value="longest_ago">Longest Ago</option>
</select>
<%= submit_tag 'Filter Results' %>
<% end %>

<% @appointments.each do |appointment |%>
<p>
    <%= link_to appointment.pet.name, pet_path(appointment.pet) %> has an appointment at 
    <%= link_to appointment.start_time.strftime('%b %e, %l:%M %p'), appointment_path(appointment) %> with 
    <%= link_to appointment.vet_name, veterinarian_path(appointment.veterinarian) %>
</p>

<% end %>

app/views/appointments/new.html.erb
<h1>New Appointment</h1>

<%= render partial: 'form', locals: { appointment: @appointment } %>

app/views/appointments/show.html.erb
<h1>Appointment Details</h1>

<p>Pet: <%= link_to @appointment.pet_name, pet_path(@appointment.pet) %> </p>
<p>Veterinarian: <%= link_to @appointment.veterinarian.name, veterinarian_path(@appointment.veterinarian) %> </p>
<p>Location: <%= @appointment.location %> </p>
<p>Start Time: <%= @appointment.start_time.strftime('%b %e, %l:%M %p') %> </p>
<p>End Time: <%= @appointment.end_time.strftime('%b %e, %l:%M %p')  %> </p>

<%# link to edit appointment %>
<%= link_to 'Edit Appointment', edit_appointment_path(@appointment) %>
<%# delete appointments  %>
<%= form_tag(appointment_path(@appointment), method: :delete, style: 'display: inline-block;') do %>
<%= submit_tag "Delete Appointment" %>
<% end %>